name: python2

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build python 2.7
        run: |
          sudo apt-get -q update
          sudo apt-get install -y closure-compiler nodejs npm gettext
          sudo npm install -g jshint
          pip install Cheetah
          pip install -r CI/requirements.txt
          pip install bandit==1.6.2
          pip install six
          python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
          cheetah compile -R plugin
          python testsuite/evil_eval.py
          bandit -r plugin -f html -o bandit.html || true
          python -m flake8 --ignore=W191,E501,E302,E711,E128,E265 --extend-exclude plugin/controllers/views/ plugin/ --output-file flake8_report.txt || true
          jshint ./sourcefiles/js/ | tee jshint1_report.txt
          jshint ./sourcefiles/modern/js/ | tee jshint2_report.txt
          ./CI/create_ipk.sh
          ./CI/create_ipk.sh novxg
          ./CI/create_ipk.sh vti
          ./CI/create_ipk.sh deb
          export PKG1=$(ls -1 *_novxg.ipk)
          export PKG2=$(ls -1 *_all.ipk)
          export PKG3=$(ls -1 *_vti.ipk)
          export PKG4=$(ls -1 *_all.deb)
          mkdir Rel
          touch ./Rel/.nojekyll
          mv "${PKG1}" ./Rel
          mv "${PKG2}" ./Rel
          mv "${PKG3}" ./Rel
          mv "${PKG4}" ./Rel
          mv bandit.html ./Rel
          mv flake8_report.txt ./Rel
          mv jshint1_report.txt ./Rel
          mv jshint2_report.txt ./Rel
          cd doc
          make html
          cd build/html
          mv * ../../../Rel/
          cd ../../../

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
